export const projects = [
  {
    id: "google-emoney",
    title: "Google eMoney",
    company: "Google (via Filter)",
    image: "/images/projects/google.png",
    description: "Consumer payment platform for YouTube and Google Play in Japan",
    tags: ["Mobile", "Payments", "Google"],
    role: "Senior UX Designer",
    year: "2018–2019",
  },
  {
    id: "paypal-partner",
    title: "PayPal Partner Servicing",
    company: "PayPal (via Cognizant)",
    image: "/images/projects/paypal.png",
    description: "Self-service dashboard for PayPal Partners with real-time merchant data",
    tags: ["Dashboard", "B2B", "PayPal"],
    role: "Senior Associate UX Designer",
    year: "2016–2018",
  },
  {
    id: "chase-payments",
    title: "Chase Payments",
    company: "JPMorgan Chase",
    image: "/images/projects/chase.png",
    description: "Component-based design system for credit card, auto loan, and mortgage payments",
    tags: ["Web", "Payments", "Chase"],
    role: "UX Designer",
    year: "2014–2016",
  },
  {
    id: "chase-otp",
    title: "Chase ATM OTP",
    company: "JPMorgan Chase",
    image: "/images/projects/chase-otp.png",
    description: "Next-generation ATM access via mobile one-time password",
    tags: ["Mobile", "Security", "Chase"],
    role: "UX Designer",
    year: "2015–2016",
  },
  {
    id: "wallyhome",
    title: "Wallyhome",
    company: "Startup",
    image: "/images/projects/wallyhome.png",
    description: "Smart home sensor dashboard with improved installation flow",
    tags: ["IoT", "Dashboard", "Startup"],
    role: "UX Designer (Graduate Project)",
    year: "2013",
  },
  {
    id: "motion-design",
    title: "Motion Design Explorations",
    company: "Personal Projects",
    image: "/images/projects/motion.png",
    description: "Personal motion design work and visual explorations",
    tags: ["Motion", "Visual Design"],
    role: "Designer",
    year: "Ongoing",
  },
];

export type Project = (typeof projects)[0];
